#spring:  
#  application:  
#    name: ershuai-eureka-server  
#  
#server:  
#  port: 1001  
#    
#eureka:  
#  client:  
#    register-with-eureka: false # 是否注册自身到eureka服务器  
#    fetch-registry: false # 是否从eureka上获取注册信息  
#  instance:  
#    hostname: localhost  
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port} # 指定此实例的ip  
#    prefer-ip-address: true # 注册时使用ip而不是主机名  
#  #server:  
#    #enable-self-preservation: false # 开启保护机制  
